### ISSUE TITLE
Optimize bootstrap column generator

### ISSUE THREAD

**Issue by chrisvfritz** [hung-phan/generator-rails-react-webpack#6]
I see [your bootstrap column generator here](https://github.com/hung-phan/generator-rails-react-webpack/blob/b52624f4ac07ba4d3e5fb5aebef4b3d06d2804b2/app/templates/app/default.css.scss#L96-L128) and do something similar on many of my projects:

``` scss
@mixin bootstrap-column($name, $percent-width) {
  $grid-width: $grid-columns * $percent-width / 100;

  .col-lg-#{name} { @include make-lg-column($grid-width); }
  .col-md-#{name} { @include make-md-column($grid-width); }
  .col-sm-#{name} { @include make-sm-column($grid-width); }
  .col-xs-#{name} { @include make-xs-column($grid-width); }
}
```

This has a few advantages:
- It's shorter. :smiley: 
- It's works The Bootstrap Way, meaning it takes advantage of Bootstrap's variables and mixins, so that if a user overrides some variables involved in grid building, this will still work as expected.
- It's much more future-proof, as future changes to the Bootstrap grid would likely only update the internal workings of their `make-SIZE-column` mixin.
